export type ItemCategory = "auras" | "families" | "perks" | "cosmetics" | "artifacts";
export type ItemTrend = "rising" | "stable" | "falling";
export type ItemRarity = "mythic" | "legendary" | "epic" | "rare" | "uncommon" | "common" | "event";

export type ValueItem = {
  id: string;
  name: string;
  category: ItemCategory;
  rarity: ItemRarity;
  value: number;
  valueKeys?: number;
  valueMasks?: number;
  valueScrolls?: number;
  valueHistory?: ValueHistoryPoint[];
  demand: number;
  trend: ItemTrend;
  taxGems: number;
  prestige: number;
  iconUrl?: string;
  source?: string;
  owners: string;
  note: string;
};

export type ValueHistoryPoint = {
  date: string;
  value: number;
};

export const categories: { id: "all" | ItemCategory; label: string }[] = [
  { id: "all", label: "All" },
  { id: "auras", label: "Auras" },
  { id: "families", label: "Families" },
  { id: "perks", label: "Perks" },
  { id: "cosmetics", label: "Cosmetics" },
  { id: "artifacts", label: "Artifacts" },
];

export const valueItems: ValueItem[] = [
  {
    "id": "tojis-attire",
    "name": "Toji's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 46800,
    "demand": 70,
    "trend": "stable",
    "taxGems": 5625,
    "prestige": 3,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/toji.png",
    "owners": "Legendary",
    "note": "High interest item with reliable trade activity."
  },
  {
    "id": "primeras-attire",
    "name": "Primera's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 19800,
    "demand": 60,
    "trend": "stable",
    "taxGems": 5625,
    "prestige": 3,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/primera.png",
    "owners": "Legendary",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "captains-attire",
    "name": "Captain's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 4050,
    "demand": 80,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 2,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/captain.png",
    "owners": "Epic",
    "note": "High interest item with reliable trade activity."
  },
  {
    "id": "quincys-attire",
    "name": "Quincy's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 1440,
    "demand": 30,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 2,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/quincy.png",
    "owners": "Epic",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "bunny-girls-attire",
    "name": "Bunny Girl's Attire",
    "category": "cosmetics",
    "rarity": "mythic",
    "value": 900,
    "demand": 50,
    "trend": "falling",
    "taxGems": 15000,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/bunny-girl.png",
    "owners": "Mythic",
    "note": "Recent listings are pulling the value down."
  },
  {
    "id": "getos-attire",
    "name": "Geto's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 900,
    "demand": 10,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/geto.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "ulquiorras-attire",
    "name": "Ulquiorra's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 540,
    "demand": 80,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/ulquiorra.png",
    "owners": "Rare",
    "note": "High interest item with reliable trade activity."
  },
  {
    "id": "soul-reapers-attire",
    "name": "Soul Reaper's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 360,
    "demand": 80,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/soul-reaper.png",
    "owners": "Uncommon",
    "note": "High interest item with reliable trade activity."
  },
  {
    "id": "shadows-attire",
    "name": "Shadow's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 270,
    "demand": 80,
    "trend": "falling",
    "taxGems": 5625,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/shadow.png",
    "owners": "Legendary",
    "note": "Current listings are above fair trade value."
  },
  {
    "id": "berserkers-attire",
    "name": "Berserker's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 270,
    "demand": 70,
    "trend": "falling",
    "taxGems": 5625,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/berserker.png",
    "owners": "Legendary",
    "note": "Current listings are above fair trade value."
  },
  {
    "id": "madaras-attire",
    "name": "Madara's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 180,
    "demand": 60,
    "trend": "stable",
    "taxGems": 5625,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/madara.png",
    "owners": "Legendary",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "sorcerers-attire",
    "name": "Sorcerer's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 180,
    "demand": 30,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/sorcerer.png",
    "owners": "Rare",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "kisukes-attire",
    "name": "Kisuke's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 180,
    "demand": 20,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/kisuke.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "maids-attire",
    "name": "Maid's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 180,
    "demand": 20,
    "trend": "stable",
    "taxGems": 4500,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/maid.png",
    "owners": "Legendary",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "gilgameshs-attire",
    "name": "Gilgamesh's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 135,
    "demand": 40,
    "trend": "stable",
    "taxGems": 5625,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/gilgamesh.png",
    "owners": "Legendary",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "shoguns-attire",
    "name": "Shogun's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 135,
    "demand": 40,
    "trend": "stable",
    "taxGems": 4500,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/shogun.png",
    "owners": "Legendary",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "giyuus-attire",
    "name": "Giyuu's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 135,
    "demand": 30,
    "trend": "stable",
    "taxGems": 5625,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/giyuu.png",
    "owners": "Legendary",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "tengens-attire",
    "name": "Tengen's Attire",
    "category": "cosmetics",
    "rarity": "legendary",
    "value": 135,
    "demand": 30,
    "trend": "stable",
    "taxGems": 5625,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/tengen.png",
    "owners": "Legendary",
    "note": "Steady market interest with usable liquidity."
  },
  {
    "id": "utahimes-attire",
    "name": "Utahime's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 90,
    "demand": 20,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/utahime.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "military-attire",
    "name": "Military Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 90,
    "demand": 10,
    "trend": "stable",
    "taxGems": 0,
    "prestige": 1,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/military.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "maidens-attire",
    "name": "Maiden's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 45,
    "demand": 10,
    "trend": "stable",
    "taxGems": 1200,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/maiden.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "akatsukis-attire",
    "name": "Akatsuki's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 35,
    "demand": 20,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/akatsuki.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "sasukes-attire",
    "name": "Sasuke's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 35,
    "demand": 20,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/sasuke.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "astolfo-2-s-attire",
    "name": "Astolfo [2]'s Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 20,
    "demand": 20,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/astolfo-2.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "astolfo-2-s-attire-astolfo",
    "name": "Astolfo [2]'s Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 20,
    "demand": 20,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/astolfo.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "archers-attire",
    "name": "Archer's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 20,
    "demand": 10,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/archer.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "pirates-attire",
    "name": "Pirate's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 15,
    "demand": 20,
    "trend": "stable",
    "taxGems": 1200,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/pirate.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "rengokus-attire",
    "name": "Rengoku's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 15,
    "demand": 10,
    "trend": "stable",
    "taxGems": 1500,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/rengoku.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "steampunkers-attire",
    "name": "Steampunker's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 15,
    "demand": 10,
    "trend": "stable",
    "taxGems": 1200,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/steampunk.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "kennys-attire",
    "name": "Kenny's Attire",
    "category": "cosmetics",
    "rarity": "epic",
    "value": 10,
    "demand": 10,
    "trend": "stable",
    "taxGems": 1200,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/kenny.png",
    "owners": "Epic",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "detectives-attire",
    "name": "Detective's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 120,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/detective.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "jolly-mascots-attire",
    "name": "Jolly Mascot's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 120,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/jolly-mascot.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "pajamas-attire",
    "name": "Pajama's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 240,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/pajama.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "santas-attire",
    "name": "Santa's Attire",
    "category": "cosmetics",
    "rarity": "event",
    "value": 5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 0,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/santa.png",
    "owners": "Events",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "cowboys-attire",
    "name": "Cowboy's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 3,
    "demand": 10,
    "trend": "stable",
    "taxGems": 240,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/cowboy.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "mikus-attire",
    "name": "Miku's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 3,
    "demand": 10,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/miku.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "narutos-attire",
    "name": "Naruto's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 3,
    "demand": 10,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/naruto.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "sabers-attire",
    "name": "Saber's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 3,
    "demand": 10,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/saber.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "saitamas-attire",
    "name": "Saitama's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 3,
    "demand": 10,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/saitama.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "tanjiros-attire",
    "name": "Tanjiro's Attire",
    "category": "cosmetics",
    "rarity": "rare",
    "value": 3,
    "demand": 10,
    "trend": "stable",
    "taxGems": 300,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/tanjiro.png",
    "owners": "Rare",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "bananas-attire",
    "name": "Banana's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 120,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/banana.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "chefs-attire",
    "name": "Chef's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 120,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/chef.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "hinatas-attire",
    "name": "Hinata's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/hinata.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "ninja-wars-attire",
    "name": "Ninja War's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/ninja-war.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "ninjas-attire",
    "name": "Ninja's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 120,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/ninja.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "shinobus-attire",
    "name": "Shinobu's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/shinobu.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "bikinis-attire",
    "name": "Bikini's Attire",
    "category": "cosmetics",
    "rarity": "uncommon",
    "value": 1,
    "demand": 10,
    "trend": "stable",
    "taxGems": 150,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/bikini.png",
    "owners": "Uncommon",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "gokus-attire",
    "name": "Goku's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 1,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/goku.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "idols-attire",
    "name": "Idol's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 1,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/idol.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "monks-attire",
    "name": "Monk's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 1,
    "demand": 10,
    "trend": "stable",
    "taxGems": 30,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/monk.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "rock-lees-attire",
    "name": "Rock Lee's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 1,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/rock-lee.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "priests-attire",
    "name": "Priest's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 0.5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/priest.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "scathatchs-attire",
    "name": "Scathatch's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 0.5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/scathach.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "slayer-m-s-attire",
    "name": "Slayer (M)'s Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 0.5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/slayer-f.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "slayer-m-s-attire-slayer-m",
    "name": "Slayer (M)'s Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 0.5,
    "demand": 10,
    "trend": "stable",
    "taxGems": 37,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/slayer-m.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  },
  {
    "id": "citizens-attire",
    "name": "Citizen's Attire",
    "category": "cosmetics",
    "rarity": "common",
    "value": 0.2,
    "demand": 10,
    "trend": "stable",
    "taxGems": 30,
    "prestige": 0,
    "iconUrl": "https://pub-d0c3b53d48004380bf4f8c053c4de0a4.r2.dev/items/citizen.png",
    "owners": "Common",
    "note": "Low-volume cosmetic, best checked against recent offers."
  }
];

export function getItemSource(item: ValueItem) {
  if (item.source) return item.source;
  if (item.rarity === "event") return "Event reward";
  if (item.category === "cosmetics") return "Cosmetic crate";
  if (item.category === "auras") return "Aura system";
  if (item.category === "families") return "Family system";
  if (item.category === "perks") return "Perk system";
  if (item.category === "artifacts") return "Artifact system";
  return "Unknown source";
}

export function getItemValueHistory(item: ValueItem) {
  return item.valueHistory ?? [];
}

export const updateLog = [
  {
    date: "May 26",
    item: valueItems[0]?.name ?? "Market",
    change: "Updated",
    reason: "Value data imported from the published AOTR value sheet.",
  },
  {
    date: "May 26",
    item: "Cosmetics",
    change: "56 items",
    reason: "Local item art has been matched to spreadsheet values.",
  },
  {
    date: "May 26",
    item: "Demand",
    change: "0-100",
    reason: "Spreadsheet demand scores are normalized for faster scanning.",
  },
];
